homeassistant:
  name: Home
  latitude: 52.1129711
  longitude: 5.1005128
  unit_system: metric
  time_zone: Europe/Amsterdam

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
